import { AlertTriangle, ArrowDownToLine, PackageCheck, RefreshCw } from 'lucide-react';
import { nationalStockInventory } from '@/lib/data';

export default function StockPage() {
  const critical = nationalStockInventory.filter(item => item.status === 'Kritis').length;
  const totalStock = nationalStockInventory.reduce((sum, item) => sum + item.stock, 0);
  return <div className="page"><div className="eyebrow">Logistik nasional / Persediaan antibiotik</div><div className="page-heading"><div><h1>Stok antibiotik Indonesia</h1><p className="subtitle">Pantau ketersediaan, laju pengeluaran, dan kebutuhan reorder lintas 38 provinsi.</p></div><button className="btn ghost"><RefreshCw size={15}/> Sinkronkan stok</button></div><div className="grid kpis"><Kpi label="Total stok terpantau" value={`${(totalStock / 1000).toFixed(1)}k`} detail={`${nationalStockInventory.length} item • 38 provinsi`} /><Kpi label="Item perlu reorder" value={String(critical)} detail="Prioritas distribusi hari ini" alert /><Kpi label="Provinsi terhubung" value="38" detail="Agregator aktif nasional" /><Kpi label="Reserve terpantau" value="308" detail="Unit lini terakhir" /></div><section className="card stock-summary"><div className="summary-callout"><PackageCheck size={22}/><div><strong>Ketersediaan nasional terkendali</strong><p className="meta">Stok Access mendominasi. Item Watch di bawah titik reorder diprioritaskan untuk redistribusi.</p></div></div></section><section className="card" style={{marginTop:18}}><div className="section-title"><span>Inventaris lintas 38 provinsi</span><span className="meta">Pembaruan 5 menit lalu</span></div><div className="table-wrap"><table><thead><tr><th>Provinsi</th><th>Antibiotik</th><th>AWaRe</th><th>Stok tersedia</th><th>Keluar/bulan</th><th>Titik reorder</th><th>Status</th><th></th></tr></thead><tbody>{nationalStockInventory.map(item => <tr key={`${item.province}-${item.medicine}`}><td><strong>{item.province}</strong></td><td>{item.medicine}</td><td><span className={`badge ${item.aware === 'Access' ? 'green' : item.aware === 'Reserve' ? 'red' : 'yellow'}`}>{item.aware}</span></td><td>{item.stock.toLocaleString('id-ID')} unit</td><td>{item.monthlyOut.toLocaleString('id-ID')}</td><td>{item.reorderPoint.toLocaleString('id-ID')}</td><td><span className={`badge ${item.status === 'Kritis' ? 'red' : item.status === 'Waspada' ? 'yellow' : 'green'}`}>{item.status}</span></td><td>{item.status === 'Kritis' && <button className="icon-action" title="Ajukan reorder"><ArrowDownToLine size={16}/></button>}</td></tr>)}</tbody></table></div></section></div>;
}
function Kpi({label, value, detail, alert}: {label:string; value:string; detail:string; alert?:boolean}) { return <div className={`card ${alert ? 'stock-kpi-alert' : ''}`}><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="meta">{detail}</div></div>; }
