'use client';

import { ArrowUpRight, Clock3, FileSearch, Flame, MapPin, ShieldAlert } from 'lucide-react';
import { anomalyCases } from '@/lib/data';

export default function AnomalyPage() {
  const red = anomalyCases.filter(item => item.flag === 'Red Flag').length;
  const yellow = anomalyCases.filter(item => item.flag === 'Yellow Flag').length;
  return <div className="page"><div className="eyebrow">Early Warning System / Local Aggregator Hub</div><div className="page-heading"><div><h1>Anomali & Investigasi</h1><p className="subtitle">Deteksi dini transaksi antibiotik berisiko dan tindak lanjut terukur Dinas Kesehatan.</p></div><span className="live-pill"><i /> MONITORING AKTIF</span></div><div className="grid kpis anomaly-kpis"><Kpi icon={<ShieldAlert size={18}/>} label="Total anomali aktif" value="128" detail="Kasus lintas wilayah" /><Kpi icon={<Flame size={18}/>} label="Kritis / Red Flag" value={`${red + 12}`} detail="Butuh penanganan cepat" alert /><Kpi icon={<FileSearch size={18}/>} label="Waspada / Yellow Flag" value={`${yellow + 108}`} detail="Perlu dipantau" /><Kpi icon={<Clock3 size={18}/>} label="Rata-rata waktu respon" value="1,2 hari" detail="Target maksimal 3 hari" /></div><section className="card anomaly-flow"><div className="flow-step active"><b>01</b><span>Deteksi otomatis</span><small>Aggregator menganalisis transaksi</small></div><ArrowUpRight size={18}/><div className="flow-step"><b>02</b><span>Review Dinkes</span><small>Validasi bukti dan tingkat risiko</small></div><ArrowUpRight size={18}/><div className="flow-step"><b>03</b><span>Tindak lanjut</span><small>Investigasi, audit, atau rekomendasi</small></div></section><section className="card"><div className="section-title"><span>Daftar anomali aktif</span><span className="meta">{anomalyCases.length} kasus prioritas ditampilkan</span></div><div className="table-wrap"><table><thead><tr><th>ID Anomali</th><th>Apotek & lokasi</th><th>Jenis indikasi pelanggaran</th><th>Risiko</th><th>Waktu</th><th>Aksi</th></tr></thead><tbody>{anomalyCases.map(item => <tr key={item.id}><td><strong>#{item.id}</strong><br/><span className="meta">Skor {item.score}/100</span></td><td><strong>{item.pharmacy}</strong><br/><span className="meta"><MapPin size={12}/> {item.location}</span></td><td><strong>{item.type}</strong><br/><span className="meta">{item.description}</span></td><td><span className={`badge ${item.flag === 'Red Flag' ? 'red' : 'yellow'}`}>{item.flag}</span></td><td className="meta">{item.created}</td><td><a className="btn small-btn" href={`/investigasi?case=${item.id}`}>{item.status === 'Baru Masuk' ? 'Buka investigasi' : 'Tinjau detail'} <ArrowUpRight size={14}/></a></td></tr>)}</tbody></table></div></section></div>;
}
function Kpi({icon, label, value, detail, alert}: {icon:React.ReactNode; label:string; value:string; detail:string; alert?:boolean}) { return <div className={`card report-kpi ${alert ? 'report-alert' : ''}`}><div className="report-kpi-icon">{icon}</div><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="meta">{detail}</div></div>; }
