export type Role = 'dinkes' | 'apoteker';
export type Flag = 'Red Flag' | 'Yellow Flag';

export const pharmacies = [
  { name: 'Apotek Sehat Sentosa', city: 'Bandung', prescriptions: 482, compliance: 96, flag: 'Red Flag' as Flag, detail: 'Penjualan Amoxicillin 2.4x di atas baseline' },
  { name: 'Apotek Kimia Farma 04', city: 'Bekasi', prescriptions: 361, compliance: 88, flag: 'Yellow Flag' as Flag, detail: 'Kelengkapan resep menurun 7% minggu ini' },
  { name: 'Klinik Medika Utama', city: 'Bogor', prescriptions: 247, compliance: 91, flag: 'Yellow Flag' as Flag, detail: 'Rasio stok dan resep tidak seimbang' },
  { name: 'Apotek Bina Sehat', city: 'Depok', prescriptions: 226, compliance: 86, flag: 'Red Flag' as Flag, detail: 'Dispensing tanpa resep meningkat 31%' },
  { name: 'Apotek Nusantara', city: 'Cirebon', prescriptions: 194, compliance: 90, flag: 'Yellow Flag' as Flag, detail: 'Klaim stok tidak sesuai mutasi' },
  { name: 'RSUD Harapan Mulya', city: 'Sukabumi', prescriptions: 178, compliance: 93, flag: 'Yellow Flag' as Flag, detail: 'Cefixime melewati ambang historis' },
  { name: 'Apotek Prima Medika', city: 'Tasikmalaya', prescriptions: 162, compliance: 84, flag: 'Red Flag' as Flag, detail: 'Pola resep berulang dari pasien sama' },
  { name: 'Klinik Pratama Sejahtera', city: 'Garut', prescriptions: 151, compliance: 95, flag: 'Yellow Flag' as Flag, detail: 'Pelaporan transaksi terlambat 2 hari' },
  { name: 'Apotek Citra Husada', city: 'Karawang', prescriptions: 139, compliance: 89, flag: 'Yellow Flag' as Flag, detail: 'Rasio Watch terhadap Access meningkat' },
  { name: 'Apotek Mitra Keluarga', city: 'Purwakarta', prescriptions: 121, compliance: 87, flag: 'Red Flag' as Flag, detail: 'Lonjakan stok keluar tanpa diagnosis' },
];

export const provinces = [
  { name: 'Jawa Barat', code: 'JB', prescriptions: '12.847', compliance: '94,8%', anomalies: 23, level: 'Tinggi' }, { name: 'Jawa Timur', code: 'JT', prescriptions: '11.392', compliance: '92,5%', anomalies: 18, level: 'Tinggi' }, { name: 'Jawa Tengah', code: 'JTG', prescriptions: '10.845', compliance: '95,1%', anomalies: 12, level: 'Stabil' }, { name: 'DKI Jakarta', code: 'JK', prescriptions: '9.762', compliance: '96,3%', anomalies: 9, level: 'Stabil' }, { name: 'Banten', code: 'BT', prescriptions: '8.421', compliance: '91,8%', anomalies: 16, level: 'Waspada' }, { name: 'Sumatera Utara', code: 'SU', prescriptions: '7.934', compliance: '89,4%', anomalies: 21, level: 'Waspada' }, { name: 'Sulawesi Selatan', code: 'SS', prescriptions: '6.718', compliance: '93,7%', anomalies: 8, level: 'Stabil' }, { name: 'DI Yogyakarta', code: 'YO', prescriptions: '4.386', compliance: '97,2%', anomalies: 4, level: 'Stabil' }, { name: 'Bali', code: 'BA', prescriptions: '4.018', compliance: '94,1%', anomalies: 7, level: 'Stabil' }, { name: 'Kalimantan Timur', code: 'KT', prescriptions: '3.592', compliance: '90,6%', anomalies: 13, level: 'Waspada' },
];
export const provinceNames = ['Aceh', 'Sumatera Utara', 'Sumatera Barat', 'Riau', 'Kepulauan Riau', 'Jambi', 'Sumatera Selatan', 'Kepulauan Bangka Belitung', 'Bengkulu', 'Lampung', 'DKI Jakarta', 'Jawa Barat', 'Jawa Tengah', 'DI Yogyakarta', 'Jawa Timur', 'Banten', 'Bali', 'Nusa Tenggara Barat', 'Nusa Tenggara Timur', 'Kalimantan Barat', 'Kalimantan Tengah', 'Kalimantan Selatan', 'Kalimantan Timur', 'Kalimantan Utara', 'Sulawesi Utara', 'Sulawesi Tengah', 'Sulawesi Selatan', 'Sulawesi Tenggara', 'Gorontalo', 'Sulawesi Barat', 'Maluku', 'Maluku Utara', 'Papua', 'Papua Barat', 'Papua Selatan', 'Papua Tengah', 'Papua Pegunungan', 'Papua Barat Daya'];
export const allProvinces = provinceNames.map((name, index) => ({ name, code: name.split(' ').map(word => word[0]).join('').slice(0, 3).toUpperCase(), prescriptions: (3280 + (index * 731) % 11200).toLocaleString('id-ID'), compliance: `${(89.2 + ((index * 7) % 82) / 10).toFixed(1).replace('.', ',')}%`, anomalies: 4 + ((index * 5) % 24), level: index % 7 === 0 ? 'Waspada' : index % 5 === 0 ? 'Tinggi' : 'Stabil' }));
export const metrics = { prescriptions: '12.847', compliance: '94,8%', anomalies: '23', pharmacies: '186' };
export const trend = [42, 58, 51, 70, 63, 82, 76, 92, 73, 84, 68, 79];
export const recentTransactions = [
  { id: 'RX-2026-0912', patient: 'P•••••• R••••', medicine: 'Amoxicillin 500mg', category: 'Access', status: 'Terverifikasi' },
  { id: 'RX-2026-0911', patient: 'A•••••• S••••', medicine: 'Cefixime 200mg', category: 'Watch', status: 'Karantina' },
  { id: 'RX-2026-0910', patient: 'D•••••• K••••', medicine: 'Azithromycin 500mg', category: 'Watch', status: 'Terverifikasi' },
  { id: 'RX-2026-0909', patient: 'S•••••• M••••', medicine: 'Ciprofloxacin 500mg', category: 'Watch', status: 'Terverifikasi' }, { id: 'RX-2026-0908', patient: 'F•••••• A••••', medicine: 'Amoxicillin 500mg', category: 'Access', status: 'Terverifikasi' }, { id: 'RX-2026-0907', patient: 'N•••••• H••••', medicine: 'Meropenem 1g', category: 'Reserve', status: 'Karantina' }, { id: 'RX-2026-0906', patient: 'R•••••• P••••', medicine: 'Doxycycline 100mg', category: 'Access', status: 'Terverifikasi' }, { id: 'RX-2026-0905', patient: 'M•••••• L••••', medicine: 'Ceftriaxone 1g', category: 'Watch', status: 'Terverifikasi' }, { id: 'RX-2026-0904', patient: 'Y•••••• T••••', medicine: 'Gentamicin 80mg', category: 'Access', status: 'Terverifikasi' }, { id: 'RX-2026-0903', patient: 'B•••••• J••••', medicine: 'Linezolid 600mg', category: 'Reserve', status: 'Karantina' }, { id: 'RX-2026-0902', patient: 'K•••••• W••••', medicine: 'Clindamycin 300mg', category: 'Watch', status: 'Terverifikasi' }, { id: 'RX-2026-0901', patient: 'T•••••• N••••', medicine: 'Azithromycin 500mg', category: 'Watch', status: 'Terverifikasi' },
];

export const stockInventory = [
  { province: 'Jawa Barat', medicine: 'Amoxicillin 500mg', aware: 'Access', stock: 18420, monthlyOut: 9230, reorderPoint: 5000, status: 'Aman' }, { province: 'Jawa Timur', medicine: 'Cefixime 200mg', aware: 'Watch', stock: 3820, monthlyOut: 4140, reorderPoint: 4500, status: 'Kritis' }, { province: 'Jawa Tengah', medicine: 'Azithromycin 500mg', aware: 'Watch', stock: 6740, monthlyOut: 2980, reorderPoint: 4000, status: 'Waspada' }, { province: 'DKI Jakarta', medicine: 'Amoxicillin 500mg', aware: 'Access', stock: 22100, monthlyOut: 11020, reorderPoint: 6000, status: 'Aman' }, { province: 'Banten', medicine: 'Ciprofloxacin 500mg', aware: 'Watch', stock: 2940, monthlyOut: 2510, reorderPoint: 3000, status: 'Waspada' }, { province: 'Sumatera Utara', medicine: 'Ceftriaxone 1g', aware: 'Watch', stock: 1280, monthlyOut: 1640, reorderPoint: 1800, status: 'Kritis' }, { province: 'Sulawesi Selatan', medicine: 'Doxycycline 100mg', aware: 'Access', stock: 4860, monthlyOut: 1920, reorderPoint: 2500, status: 'Aman' }, { province: 'DI Yogyakarta', medicine: 'Meropenem 1g', aware: 'Reserve', stock: 210, monthlyOut: 42, reorderPoint: 100, status: 'Aman' }, { province: 'Bali', medicine: 'Clindamycin 300mg', aware: 'Watch', stock: 2140, monthlyOut: 1180, reorderPoint: 1500, status: 'Aman' }, { province: 'Kalimantan Timur', medicine: 'Linezolid 600mg', aware: 'Reserve', stock: 98, monthlyOut: 27, reorderPoint: 60, status: 'Aman' }, { province: 'Sumatera Barat', medicine: 'Gentamicin 80mg', aware: 'Access', stock: 1760, monthlyOut: 880, reorderPoint: 1000, status: 'Aman' }, { province: 'Nusa Tenggara Barat', medicine: 'Cefixime 200mg', aware: 'Watch', stock: 920, monthlyOut: 1340, reorderPoint: 1200, status: 'Kritis' },
];
export const nationalStockInventory = provinceNames.map((province, index) => { const medicines = ['Amoxicillin 500mg', 'Cefixime 200mg', 'Azithromycin 500mg', 'Ciprofloxacin 500mg', 'Ceftriaxone 1g']; const aware = ['Access', 'Watch', 'Watch', 'Watch', 'Watch']; const stock = 1800 + ((index * 1731) % 19000); const monthlyOut = 700 + ((index * 911) % 8500); const reorderPoint = Math.round(monthlyOut * 0.65); const status = stock < reorderPoint ? 'Kritis' : stock < reorderPoint * 1.35 ? 'Waspada' : 'Aman'; return { province, medicine: medicines[index % medicines.length], aware: aware[index % aware.length], stock, monthlyOut, reorderPoint, status }; });

export const awareReport = [{ category: 'Access', count: 84260, percentage: 68.4, examples: 'Amoxicillin, Doxycycline' }, { category: 'Watch', count: 37320, percentage: 30.3, examples: 'Cefixime, Ciprofloxacin' }, { category: 'Reserve', count: 1605, percentage: 1.3, examples: 'Meropenem, Linezolid' }];
export const reportMetrics = { reused: 342, rejected: 128, realtime: '91,6%', validPrescription: '94,8%', backlog: '8,4%' };
export const complianceReport = [{ name: 'Klinik Pratama Sejahtera', province: 'Jawa Barat', realtime: 99.2, validation: 98.8, score: 98.9, status: 'Paling patuh' }, { name: 'Apotek Sehat Sentosa', province: 'Jawa Barat', realtime: 97.5, validation: 96.2, score: 96.8, status: 'Paling patuh' }, { name: 'RSUD Harapan Mulya', province: 'Jawa Tengah', realtime: 95.8, validation: 94.4, score: 95.1, status: 'Paling patuh' }, { name: 'Apotek Nusantara', province: 'Banten', realtime: 88.2, validation: 86.4, score: 87.3, status: 'Pengawasan' }, { name: 'Apotek Bina Sehat', province: 'Jawa Barat', realtime: 84.7, validation: 82.1, score: 83.4, status: 'Pengawasan' }, { name: 'Apotek Prima Medika', province: 'Jawa Barat', realtime: 81.6, validation: 79.4, score: 80.5, status: 'Pengawasan' }];
const complianceNames = ['Apotek Aceh Sehat', 'Klinik Medika Utara', 'Apotek Minang Jaya', 'RSUD Lancang Kuning', 'Apotek Kepri Farma', 'Apotek Batanghari', 'Klinik Sriwijaya', 'Apotek Babel Sehat', 'Apotek Rafflesia', 'Apotek Lampung Medika', 'Apotek Sehat Jakarta', 'Apotek Sehat Sentosa', 'Klinik Pratama Sejahtera', 'RSUD Harapan Mulya', 'Apotek Prima Medika', 'Apotek Bina Sehat', 'Apotek Bali Husada', 'Apotek Sasambo', 'Klinik Flobamora', 'Apotek Borneo Sehat', 'Apotek Etam Farma', 'Apotek Banua Medika', 'Apotek Mahakam', 'Apotek Kaltara Sehat', 'Apotek Celebes Farma'];
export const nationalComplianceReport = complianceNames.map((name, index) => { const realtime = Number((82.4 + ((index * 13) % 177) / 10).toFixed(1)); const validation = Number((80.8 + ((index * 17) % 190) / 10).toFixed(1)); return { name, province: provinceNames[(index * 3) % provinceNames.length], realtime, validation, score: Number(((realtime + validation) / 2).toFixed(1)), status: realtime > 92 ? 'Paling patuh' : 'Pengawasan' }; });
export const atcDddReport = [{ region: 'Bandung', values: [58, 63, 61, 70, 74, 79] }, { region: 'Surabaya', values: [64, 67, 72, 76, 82, 88] }, { region: 'Jakarta', values: [71, 69, 73, 72, 75, 77] }, { region: 'Medan', values: [52, 58, 61, 65, 69, 73] }, { region: 'Makassar', values: [44, 48, 53, 55, 59, 62] }];
export const nationalAtcDddReport = allProvinces.map((province, index) => ({ region: province.name, values: Array.from({ length: 12 }, (_, month) => Number((42 + ((index * 11 + month * (2 + index % 4)) % 61)).toFixed(1))) }));
export const anomalyCases = [
  { id: 'ANM-2026-042', pharmacy: 'Apotek Sehat Sentosa', location: 'Kec. Sukarami, Bandung', type: 'Lonjakan Penjualan Irasional', description: 'Penjualan Azithromycin naik 300% dalam 3 hari tanpa resep atau diagnosis yang sesuai.', flag: 'Red Flag' as Flag, created: '23 Sep 2026, 09:14 WIB', score: 92, status: 'Baru Masuk' },
  { id: 'ANM-2026-041', pharmacy: 'Apotek Bina Sehat', location: 'Kec. Beji, Depok', type: 'Percobaan Resep Ganda', description: 'Kode QR RX-2026-0901 telah dikunci oleh Apotek Kimia Farma 04.', flag: 'Red Flag' as Flag, created: '23 Sep 2026, 08:42 WIB', score: 88, status: 'Dalam Audit Lapangan' },
  { id: 'ANM-2026-040', pharmacy: 'Apotek Prima Medika', location: 'Kec. Cihideung, Tasikmalaya', type: "Dominasi Kategori WHO 'Watch' / 'Reserve'", description: 'Ceftriaxone dan Meropenem terjual tanpa lampiran ICD-10 spesialis.', flag: 'Red Flag' as Flag, created: '22 Sep 2026, 16:20 WIB', score: 86, status: 'Menunggu Klarifikasi' },
  { id: 'ANM-2026-039', pharmacy: 'Apotek Kimia Farma 04', location: 'Kec. Bekasi Selatan, Bekasi', type: 'Discrepancy Stok (Off-book sales)', description: 'Stok Cefixime berkurang 86 unit tanpa pencatatan resep terikat.', flag: 'Yellow Flag' as Flag, created: '22 Sep 2026, 14:08 WIB', score: 71, status: 'Baru Masuk' },
  { id: 'ANM-2026-038', pharmacy: 'Apotek Nusantara', location: 'Kec. Kesambi, Cirebon', type: 'Discrepancy Stok (Off-book sales)', description: 'Mutasi stok terlambat dilaporkan selama 48 jam.', flag: 'Yellow Flag' as Flag, created: '22 Sep 2026, 11:35 WIB', score: 64, status: 'Menunggu Klarifikasi' },
  { id: 'ANM-2026-037', pharmacy: 'Klinik Medika Utama', location: 'Kec. Bogor Tengah, Bogor', type: 'Percobaan Resep Ganda', description: 'Tiga percobaan scan pada QR resep yang sudah ditebus.', flag: 'Yellow Flag' as Flag, created: '21 Sep 2026, 17:48 WIB', score: 62, status: 'Selesai / Diberi Sanksi' },
  { id: 'ANM-2026-036', pharmacy: 'RSUD Harapan Mulya', location: 'Kec. Cikole, Sukabumi', type: 'Lonjakan Penjualan Irasional', description: 'Pengeluaran Cefixime 1,8x di atas baseline mingguan.', flag: 'Yellow Flag' as Flag, created: '21 Sep 2026, 13:02 WIB', score: 59, status: 'Baru Masuk' },
  { id: 'ANM-2026-035', pharmacy: 'Apotek Mitra Keluarga', location: 'Kec. Purwakarta, Purwakarta', type: "Dominasi Kategori WHO 'Watch' / 'Reserve'", description: 'Rasio Watch terhadap Access melewati ambang wilayah.', flag: 'Red Flag' as Flag, created: '20 Sep 2026, 10:17 WIB', score: 83, status: 'Dalam Audit Lapangan' },
];
export const auditTrail = [{ date: '24 Sep 2026 • 10:22 WIB', actor: 'Dinkes Jawa Barat', action: 'Menerbitkan SP-1 elektronik kepada Apotek Sehat Sentosa.' }, { date: '23 Sep 2026 • 15:40 WIB', actor: 'Sistem TILIK', action: 'Membuat laporan investigasi otomatis dari 42 transaksi bukti.' }, { date: '23 Sep 2026 • 09:14 WIB', actor: 'Local Aggregator Hub', action: 'Mendeteksi lonjakan Azithromycin dan menaikkan kasus ke Red Flag.' }];

export const entityRelationship = {
  users: ['id', 'role', 'identity_number', 'facility_id'],
  facilities: ['id', 'name', 'city', 'license_number'],
  prescriptions: ['id', 'qr_code', 'patient_hash', 'diagnosis', 'doctor_id', 'pharmacist_id', 'status', 'dispensed_at'],
  prescription_items: ['id', 'prescription_id', 'medicine_id', 'quantity', 'aware_category', 'atc_code', 'ddd_value'],
  medicines: ['id', 'name', 'atc_code', 'aware_category', 'ddd_standard'],
  stock_movements: ['id', 'facility_id', 'medicine_id', 'movement_type', 'quantity', 'created_at'],
  anomalies: ['id', 'facility_id', 'severity', 'reason', 'status', 'created_at'],
  integration_logs: ['id', 'prescription_id', 'fhir_payload', 'status', 'attempts', 'last_attempt_at'],
};
