'use client';

import { AlertTriangle, ClipboardCheck, Package, ScanLine, X } from 'lucide-react';
import { useState } from 'react';
import { recentTransactions, stockInventory } from '@/lib/data';

export default function ApotekerDashboard() {
  const [modal, setModal] = useState<'prescription' | 'stock' | null>(null);
  return <div className="page pharmacist-page"><div className="eyebrow">Fasilitas kesehatan / Apotek Sehat Sentosa</div><h1>Dashboard Apoteker</h1><p className="subtitle">Aktivitas dispensasi antibiotik faskes Anda terkoneksi ke Surveillance Nasional.</p><div className="grid kpis pharmacist-kpis"><Kpi label="Resep hari ini" value="47" detail="Resep antibiotik tervalidasi" color="blue" /><Kpi label="Antibiotik terdispensasi" value="32" detail="Amoxicillin & Cefixime mendominasi" color="blue" /><Kpi label="Tingkat kepatuhan" value="96,2%" detail="Validasi anti-duplicate 100%" color="green" /><Kpi label="Peringatan stok" value="3" detail="Antibiotik kritis menipis" color="amber" /></div><div className="pharmacist-actions"><a className="btn teal" href="/scan"><ScanLine size={17}/> Pindai Resep QR</a><button className="btn ghost" onClick={() => setModal('prescription')}><ClipboardCheck size={17}/> Input manual</button><button className="btn ghost" onClick={() => setModal('stock')}><Package size={17}/> Catat mutasi stok</button></div><div className="grid pharmacist-columns"><section className="card"><div className="section-title"><span>Aktivitas pindai terakhir</span><span className="meta">{recentTransactions.length} transaksi hari ini</span></div><div className="table-wrap"><table><thead><tr><th>Waktu</th><th>Kode pasien</th><th>Antibiotik</th><th>Status</th></tr></thead><tbody>{recentTransactions.map((tx, index) => <tr key={tx.id}><td>{['14:15','13:42','11:20','10:46','09:35','08:52','08:30','08:12','07:55','07:30','07:10','06:48'][index] ?? '06:30'} WIB</td><td><strong>{tx.id.replace('RX-', 'PX-')}</strong></td><td>{tx.medicine}</td><td><span className={`badge ${tx.status === 'Karantina' ? 'red' : 'green'}`}>{tx.status === 'Karantina' ? 'Ditolak' : 'Berhasil'}</span></td></tr>)}</tbody></table></div></section><section className="card"><div className="section-title"><span>Stok antibiotik menipis</span><span className="meta">{stockInventory.length} item terpantau</span></div><div className="stock-list">{stockInventory.slice(0, 8).map(item => <Stock key={`${item.province}-${item.medicine}`} name={item.medicine} amount={`${item.stock.toLocaleString('id-ID')} unit tersisa`} status={item.status}/>)}</div><div className="stock-alert"><AlertTriangle size={17}/><span>Perhatian: item kritis perlu reorder sebelum stok habis.</span></div></section></div>{modal && <Modal type={modal} close={() => setModal(null)}/>}</div>;
}
function Kpi({label, value, detail, color}: {label:string; value:string; detail:string; color:'blue'|'green'|'amber'}) { return <div className={`card pharmacist-kpi ${color}`}><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="meta">{detail}</div></div>; }
function Stock({name, amount, status}: {name:string; amount:string; status:string}) { return <div className="stock-row"><div><strong>{name}</strong><small>{amount}</small></div><span className={`badge ${status === 'Kritis' ? 'red' : 'yellow'}`}>{status.toUpperCase()}</span><a href="/stok">Detail</a></div>; }
function Modal({type, close}: {type:'prescription'|'stock'; close:() => void}) { const prescription = type === 'prescription'; return <div className="modal-overlay" onClick={close}><section className="modal-panel" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={close}><X size={18}/></button><div className="eyebrow">{prescription ? 'Input resep baru' : 'Mutasi stok antibiotik'}</div><h2>{prescription ? 'Input resep manual' : 'Catat mutasi stok'}</h2><p className="subtitle">Data demo akan masuk ke antrean karantina untuk validasi aggregator.</p><div className="form-grid"><label>{prescription ? 'Kode resep' : 'Nama antibiotik'}<input placeholder={prescription ? 'RX-2026-0913' : 'Amoxicillin 500mg'}/></label><label>{prescription ? 'Nama pasien' : 'Jenis mutasi'}<select defaultValue={prescription ? 'pasien' : 'keluar'}><option value="pasien">P•••••• R••••</option><option value="keluar">Pengeluaran resep</option><option value="masuk">Penerimaan stok</option></select></label><label>{prescription ? 'Diagnosis / ICD-10' : 'Jumlah unit'}<input placeholder={prescription ? 'J06.9 / Infeksi saluran napas' : '100'}/></label><label>{prescription ? 'Kategori WHO AWaRe' : 'Nomor batch'}<select defaultValue="Access"><option>Access</option><option>Watch</option><option>Reserve</option></select></label></div><button className="btn teal modal-submit" onClick={close}>{prescription ? 'Simpan ke karantina' : 'Simpan mutasi stok'}</button></section></div>; }
